In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!pip install attacut

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 2.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.3/88.3 kB 8.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 473.8/473.8 kB 8.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 9.1 MB/s eta 0:00:00
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=44a8421c7926f7e751ca38bb4589a2d4a910baf74226aba8155f6b67ee877c63
  Stored in directory: /root/.cache/pip/wheels/fc/ab/d4/5da2067ac95b36618c629a5f93f809425700506f72c9732fac
  Created wheel for fire: filename=fire-0.5.0-py2.py3-none-any.whl size=116934 sha256=bb3a5523331be56e39fd7ee98c79ec74857bf5b0641f7887d3ad701e6efd7aa8
  Stored in directory: /root/.cache/pip/wheels/90/d4/f7/9404e5db0116bd4d43e5666eaa3e70ab53723e1e3ea40c9a95
Successfully built docopt fire


In [41]:
import gensim
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

import gdown
import tensorflow as tf
from tensorflow import keras
import numpy as np
import re
import math

# !pip install attacut
from attacut import tokenize

from tensorflow.keras.utils import to_categorical
# !pip install pythainlp
# from pythainlp.tokenize import word_tokenize

from matplotlib import pyplot
from keras.models import load_model
from keras.callbacks import ModelCheckpoint
from sklearn.metrics import accuracy_score

In [4]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, TimeDistributed, Conv2D,MaxPooling2D,Flatten,Reshape,Dropout, Embedding, SpatialDropout1D
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv3D, Bidirectional
from tensorflow.keras.layers import ConvLSTM2D
from tensorflow.keras.layers import BatchNormalization

In [13]:
# gdown.download('https://drive.google.com/uc?id=0B0ZXk88koS2KV1FJN0xRX1FxaFE&export=download',
#                '/content/drive/MyDrive/Thai NLP sentiment analysis/pretrained_Model/th.zip', quiet=False)

Downloading...
From: https://drive.google.com/uc?id=0B0ZXk88koS2KV1FJN0xRX1FxaFE&export=download
To: /content/drive/MyDrive/Thai NLP sentiment analysis/pretrained_Model/th.zip
100%|██████████| 122M/122M [00:02<00:00, 41.1MB/s]


'/content/drive/MyDrive/Thai NLP sentiment analysis/pretrained_Model/th.zip'

In [14]:
# !unzip '/content/drive/MyDrive/Thai NLP sentiment analysis/pretrained_Model/th.zip' -d '/content/drive/MyDrive/Thai NLP sentiment analysis/pretrained_Model'

Archive:  /content/drive/MyDrive/Thai NLP sentiment analysis/pretrained_Model/th.zip
replace /content/drive/MyDrive/Thai NLP sentiment analysis/pretrained_Model/th.bin? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace /content/drive/MyDrive/Thai NLP sentiment analysis/pretrained_Model/th.tsv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n


In [5]:
messages = pd.read_csv('/content/drive/MyDrive/Thai NLP sentiment analysis/Dataset/Train01_Clear.csv')# [:5000]
messages

Unnamed: 0     Class                                               Text
0               0   neutral  ประเทศ เรา ผลิต และ ส่งออก ยาสูบ เยอะ สุด ใน โ...
1               1   neutral                                                 คะ
2               2  negative                อิ เหี้ย ออม ทำ กู อยาก กิน เอ็ม เค
3               4   neutral                         สวัสดี วัน พุธ แนน อะไร นะ
4               5   neutral  ก้อน ขอบพระคุณ มาก นะ คร้าบ ที่ มาหา ก้อน และ ...
...           ...       ...                                                ...
23286       24058  negative                                 แม่ ง ควาย ล้วน นน
23287       24059  negative                   ดอย สุเทพ น้อง ง ไป หมด แล้ว ววว
23288       24060  negative                      ค่า ชุด อาจจะ แพง กว่า ส่วนลด
23289       24061   neutral                          รัฐ ต้องการ แค่ ภาษี ครับ
23290       24062   neutral  ได้ พัฒนา ระบบ เข้าสู่ รุ่น ที่สอง แล้ว มา ดู ...

[23291 rows x 3 columns]

In [ ]:
# messages_Lean = messages
# messages_Lean.drop(messages_Lean.loc[messages_Lean['Class']==neutral].index, inplace=True)
# messages_Lean

In [6]:
Xtrain = messages['Text'].tolist()
Xtrain[:5]

['ประเทศ เรา ผลิต และ ส่งออก ยาสูบ เยอะ สุด ใน โลก จิง ป่าว คับ',
 'คะ',
 'อิ เหี้ย ออม ทำ กู อยาก กิน เอ็ม เค',
 'สวัสดี วัน พุธ แนน อะไร นะ',
 'ก้อน ขอบพระคุณ มาก นะ คร้าบ ที่ มาหา ก้อน และ ชมเชย การ บริการ ของ พนักงาน อีกด้วย']

In [43]:
Xtrain[0]

'ประเทศ เรา ผลิต และ ส่งออก ยาสูบ เยอะ สุด ใน โลก จิง ป่าว คับ'

In [154]:
# np.array([0,0,0,1,1,1]).shape

In [18]:
# Ytrain = messages['Class'].values
# print(Ytrain[:5])
# print(Ytrain.shape)

['neutral' 'neutral' 'negative' 'neutral' 'neutral']
(23291,)


In [7]:
messages['Class onthot']=messages['Class'].map({'neutral':0, 'negative':1, 'positive':2})

YY = np.array(messages['Class onthot'])
NUM_CLASSES = len(np.unique(YY))
print('NUM_CLASSES: ', NUM_CLASSES)

# YY = YY.reshape((YY.shape[0], 1)) # 100, 21, 63

Ytrain = to_categorical(YY).astype(int)
print(Ytrain.shape)
print(Ytrain)

NUM_CLASSES:  3
(23291, 3)
[[1 0 0]
 [1 0 0]
 [0 1 0]
 ...
 [0 1 0]
 [1 0 0]
 [1 0 0]]


In [20]:
# wordvector Embedding --> th.tsv

In [8]:
with open('/content/drive/MyDrive/Thai NLP sentiment analysis/pretrained_Model/th.tsv') as f:
  vocab = []
  W = None
  vec = ''
  for line in f.readlines():
    temp = line.split('\t')
    if len(temp) == 3:
      vocab.append(temp[1])
      if int(temp[0]) % 1000 == 0:
        print('\r' + temp[0], end='')
      wordvector = np.fromstring(re.sub('\s+', ' ', vec)[1:-1], sep=' ', dtype=np.float32)
      if len(wordvector) > 0:
        if W is None:
          W = wordvector.copy()
        else:
          W = np.vstack((W, wordvector))
      vec = temp[-1]
    elif len(temp) == 1:
      vec += temp[-1]
  W = np.vstack((W, wordvector))
print('\n')
print(len(vocab))
print(W.shape)

0

<ipython-input-8-1db8993b9877>:11: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  wordvector = np.fromstring(re.sub('\s+', ' ', vec)[1:-1], sep=' ', dtype=np.float32)


30000

30225
(30225, 300)


In [9]:
vocab[:10]

['ที่', 'ใน', 'เป็น', 'การ', 'และ', '.', 'ของ', 'มี', 'ได้', 'จาก']

In [10]:
W[0]

array([ 0.5111534 , -0.42602733, -1.1047213 , -0.09861032, -0.7959196 ,
       -0.04069895, -0.4751913 , -2.4259894 , -0.9154915 , -0.6981973 ,
       -1.4204978 ,  0.41850504,  0.10783649, -1.1551229 ,  0.84297925,
        0.21317165, -0.8573801 ,  0.13308409, -1.5027136 , -0.3680748 ,
        0.17844827, -0.32479113, -0.02270988,  1.1426282 , -0.7670676 ,
        0.9499072 ,  0.8629837 , -1.115946  ,  1.8497207 , -0.7477565 ,
       -0.98457634,  0.62077665, -1.044819  ,  0.49659768,  0.7527551 ,
        0.3008537 ,  0.49309847,  1.252389  ,  1.3147308 , -0.05037038,
        2.0898983 , -0.83630407,  0.72436315, -0.4093991 ,  0.8712473 ,
       -0.35788864, -2.954445  ,  0.6072951 ,  0.45909956,  0.6013222 ,
       -0.3339661 ,  0.33911785,  0.07171268,  0.5284492 , -0.17997597,
       -0.07178577, -0.8013349 , -0.9025106 ,  0.43145105, -0.17078198,
       -0.10902111, -0.7228254 ,  1.306308  , -0.5081288 , -0.12411323,
       -0.7293398 ,  0.98485565,  0.8211375 ,  1.4071932 , -0.33

In [11]:
def sent2idx(x):
  xidx = []
  for w in tokenize(x):
    if w in vocab:
      xidx.append(vocab.index(w))
  return np.array(xidx)

In [12]:
sent2idx(Xtrain[0]) #Embedding

array([   31,   458,   313,     4,   250,    39,  5666,  3609,   230,
           1,   100, 11139,  5953])

In [13]:
sent2idx(Xtrain[0]).shape

(13,)

In [14]:
# maxlen vocab Embedding
Xtrain_idx = []
maxlen = 0
for x in Xtrain:
  Xtrain_idx.append(sent2idx(x))
  if len(Xtrain_idx[-1]) > maxlen:
    maxlen = len(Xtrain_idx[-1])
  # print(len(Xtrain_idx[-1]))

In [15]:
print(maxlen)

473


In [16]:
vocab[0]

'ที่'

In [17]:
W[0].shape

(300,)

In [18]:
# add vocab ''
vocab = [''] + vocab
print(len(vocab))

30226


In [19]:
vocab[0]

''

In [20]:
W = np.vstack((np.random.rand(*W[0].shape), W))

In [21]:
W.shape

(30226, 300)

In [22]:
print(Xtrain_idx[0].shape)
print(Xtrain_idx[5].shape)
print(Xtrain_idx[250].shape)

(13,)
(118,)
(1,)


In [23]:
for i, x in enumerate(Xtrain_idx):
  if len(x) < maxlen:
    Xtrain_idx[i] = np.hstack((x, np.zeros(maxlen-len(x))))
Xtrain_idx = np.array(Xtrain_idx)

In [24]:
# maxlen = 473
print(Xtrain_idx[0].shape)
print(Xtrain_idx[5].shape)
print(Xtrain_idx[250].shape)

(473,)
(473,)
(473,)


In [25]:
Xtrain_idx.shape

(23291, 473)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(Xtrain_idx, Ytrain, test_size=0.3, ) #random_state=3

print('X_train: ', X_train.shape)
print('y_train: ', y_train.shape)

print('X_test: ', X_test.shape)
print('y_test: ', y_test.shape)

X_train:  (16303, 473)
y_train:  (16303, 3)
X_test:  (6988, 473)
y_test:  (6988, 3)


In [27]:
W.shape

(30226, 300)

In [28]:
Class_label = 3

model = Sequential()
model.add(Embedding(W.shape[0], W.shape[1], name='embed'))
model.add(Bidirectional(LSTM(8, return_sequences=True)))
model.add(Bidirectional(LSTM(4)))
model.add(Dense(64, activation='relu'))

# model.add(keras.layers.Dense(2))
# model.compile(loss=keras.losses.sparse_categorical_crossentropy, optimizer=keras.optimizers.SGD(learning_rate=1e-4))

model.add(Dense(Class_label, activation='softmax'))
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])
# model.compile(optimizer='Adam', loss='categorical_crossentropy')

model.get_layer('embed').set_weights([W])
model.get_layer('embed').trainable = False
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embed (Embedding)           (None, None, 300)         9067800   
                                                                 
 bidirectional (Bidirectiona  (None, None, 16)         19776     
 l)                                                              
                                                                 
 bidirectional_1 (Bidirectio  (None, 8)                672       
 nal)                                                            
                                                                 
 dense (Dense)               (None, 64)                576       
                                                                 
 dense_1 (Dense)             (None, 3)                 195       
                                                                 
Total params: 9,089,019
Trainable params: 21,219
Non-tra

In [29]:
filepath_checkpoint = '/content/drive/MyDrive/Thai NLP sentiment analysis/Checkpoint_LSTM_TH/old/cp-0035.ckpt'
model.load_weights(filepath_checkpoint)
model

In [30]:
batch_size = 32
n_batches = len(X_train) / batch_size
n_batches = math.ceil(n_batches)    # round up the number of batches to the nearest whole integer

5*n_batches

2550

In [34]:
filepath_checkpoint = '/content/drive/MyDrive/Thai NLP sentiment analysis/Checkpoint_LSTM_TH/cp-0015.ckpt'
model.load_weights(filepath_checkpoint)
model

In [31]:
# Include the epoch in the file name (uses `str.format`)
checkpoint_path = "/content/drive/MyDrive/Thai NLP sentiment analysis/Checkpoint_LSTM_TH/cp-{epoch:04d}.ckpt"

# Create a callback that saves the model's weights every 5 epochs
cp_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=1,
    save_weights_only=True,
    save_freq=5*n_batches)

# Save the weights using the `checkpoint_path` format
model.save_weights(checkpoint_path.format(epoch=0))

In [32]:
# model.fit(Xtrain_idx, np.array([0,0,0,1,1,1]), epochs=10)
batch_size = 32
# train โมเดล และเก็บ log
history = model.fit(X_train, y_train, epochs=65, batch_size=batch_size, callbacks=[cp_callback],
                    validation_data=(X_test, y_test), verbose=1, shuffle=False)

Epoch 1/65
510/510 [==============================] - 584s 1s/step - loss: 0.4511 - categorical_accuracy: 0.8606 - val_loss: 0.4154 - val_categorical_accuracy: 0.8651
Epoch 2/65
510/510 [==============================] - 542s 1s/step - loss: 0.3290 - categorical_accuracy: 0.8921 - val_loss: 0.4297 - val_categorical_accuracy: 0.8558
Epoch 3/65
510/510 [==============================] - 551s 1s/step - loss: 0.2797 - categorical_accuracy: 0.9096 - val_loss: 0.4588 - val_categorical_accuracy: 0.8523
Epoch 4/65
510/510 [==============================] - 539s 1s/step - loss: 0.2479 - categorical_accuracy: 0.9189 - val_loss: 0.4915 - val_categorical_accuracy: 0.8413
Epoch 5/65
509/510 [============================>.] - ETA: 0s - loss: 0.2240 - categorical_accuracy: 0.9271
Epoch 5: saving model to /content/drive/MyDrive/Thai NLP sentiment analysis/Checkpoint_LSTM_TH/cp-0005.ckpt
510/510 [==============================] - 536s 1s/step - loss: 0.2239 - categorical_accuracy: 0.9271 - val_loss: 0.

KeyboardInterrupt: ignored

In [35]:
model.save('/content/drive/MyDrive/Thai NLP sentiment analysis/Checkpoint_LSTM_TH/LSTM_PONth35_50.h5')

In [ ]:
# พล็อตค่า train&test loss
pyplot.plot(history.history['loss'], label='train')
pyplot.plot(history.history['val_loss'], label='test')
pyplot.legend()
pyplot.show()

In [ ]:
pyplot.plot(history.history['loss'], label='train_loss')
pyplot.plot(history.history['categorical_accuracy'], label='categorical_accuracy')
pyplot.legend()
pyplot.show()

In [ ]:
## ------------- TEST Model ------------- ##

In [36]:
model_LSTMth_PON = load_model('/content/drive/MyDrive/Thai NLP sentiment analysis/Checkpoint_LSTM_TH/LSTM_PONth35_50.h5')

In [42]:
## ------------- X_test = Validation Set ------------- ##
yhat = model_LSTMth_PON.predict(X_test)

ytrue = np.argmax(y_test, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()

# multilabel_confusion_matrix(ytrue, yhat)
accuracy_score(ytrue, yhat)

219/219 [==============================] - 40s 184ms/step


0.8000858614768174

In [50]:
X_test.shape

(6988, 473)

In [51]:
X_test[0]

array([ 260.,  599.,  422., 1264.,  201.,  178.,  202.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,

In [63]:
sent2idx('สวัสดีครับ')

array([4741,  347])

In [145]:
Xtest = ['กูท้อมากหดหู่ฉิบหาย', 'สวัสดีครับ', 'ราคาดีอร่อยมาก', 'สินค้ามีการรับประกันดีมาก']
# X_test_text = ['สวัสดี','ทดสอบ','ทดทรมาน','โง่มาก', 'กูท้อมาก', 'หดหู่ฉิบหาย','เหี้ยที่สุด','เออไม่กินแล้ว','ขอบคุณจ้า','ทำดีมาก']

Xtest_idx = []
for x in Xtest:
  #print(x)
  Xtest_idx.append(sent2idx(x))
  # print('Xtest_idx: ',Xtest_idx)
  if len(Xtest_idx[-1]) > maxlen:
    Xtest_idx[-1] =  Xtest_idx[-1][:maxlen]
  else:
    Xtest_idx[-1] = np.hstack((Xtest_idx[-1], np.zeros(maxlen-len(Xtest_idx[-1]))))
Xtest_idx = np.array(Xtest_idx)

# Xtest_idx_ = Xtest_idx.reshape((Xtest_idx.shape[0], -1))

In [146]:
# predict_Text = model.predict(Xtest_idx)#.argmax(axis=1)
dic_label = {0:'neutral', 1:'negative', 2:'positive'}
yhat_P = model_LSTMth_PON.predict(Xtest_idx)

print(yhat_P)
for i, Value in enumerate(yhat_P):
  print(Xtest[i])
  print(np.argmax(Value))
  print('Predicted value is =', dic_label[np.argmax(Value)])
  print('--------')

1/1 [==============================] - 0s 98ms/step
[[7.6714758e-04 9.9856025e-01 6.7260931e-04]
 [9.9991834e-01 2.0422029e-05 6.1256353e-05]
 [9.9662328e-01 2.2942836e-04 3.1473471e-03]
 [2.8464636e-01 4.0888037e-03 7.1126485e-01]]
กูท้อมากหดหู่ฉิบหาย
1
Predicted value is = negative
--------
สวัสดีครับ
0
Predicted value is = neutral
--------
ราคาดีอร่อยมาก
0
Predicted value is = neutral
--------
สินค้ามีการรับประกันดีมาก
2
Predicted value is = positive
--------


In [ ]:
## ------------- X_test = Test Set ไม่เคยเห็นมาก่อน ------------- ##

In [147]:
messages_Test = pd.read_csv('/content/drive/MyDrive/Thai NLP sentiment analysis/Dataset/Test01_Clear.csv')# [:5000]
messages_Test

Unnamed: 0     Class                                               Text
0              0  negative  ซื้อ แต่ ผ้าอนามัย แบบ เย็น มา ค่ะ แบบ ว่า อี ...
1              1   neutral                                               ครับ
2              2  negative  การ ด่า ไป เหมือน ได้ บรรเทา ความเครียด เฉย แต...
3              3   neutral                                                ขวด
4              4   neutral  ทาน ได้ ค่ะ น้ำ ซุป ต้ม มาจาก หัวผักกาด ซีอิ้ว...
...          ...       ...                                                ...
2584        2669  positive  เล็ก ลงมา แต่ ดี เท่าเดิม แวะ มาหา ได้ที่ เซเว...
2585        2670   neutral  แพนด้า ซิ่ง กับ มุมมอง ที่ แตกต่าง อย่าง ลงตัว...
2586        2671  positive                                        ไป เถอะ ดอม
2587        2672   neutral                     เจมส์ บอนด์ ขับ โตโยต้า อัลติส
2588        2673   neutral                            จัด สิ ค่ะ บาร์ บี ก้อน

[2589 rows x 3 columns]

In [152]:
messages_Test['Class onthot']=messages_Test['Class'].map({'neutral':0, 'negative':1, 'positive':2})

YY_Test = np.array(messages_Test['Class onthot'])
NUM_CLASSES = len(np.unique(YY_Test))
print('NUM_CLASSES: ', NUM_CLASSES)

# YY = YY.reshape((YY.shape[0], 1)) # 100, 21, 63

YTest = to_categorical(YY_Test).astype(int)
print(YTest.shape)
print(YTest)

NUM_CLASSES:  3
(2589, 3)
[[0 1 0]
 [1 0 0]
 [0 1 0]
 ...
 [0 0 1]
 [1 0 0]
 [1 0 0]]


In [148]:
XTest = messages_Test['Text'].tolist()
XTest[:5]

['ซื้อ แต่ ผ้าอนามัย แบบ เย็น มา ค่ะ แบบ ว่า อี ห่า กู นอน ไม่ ได้',
 'ครับ',
 'การ ด่า ไป เหมือน ได้ บรรเทา ความเครียด เฉย แต่ บีทีเอส รถไฟฟ้า มัน สำนึก มั้ย ก็ ไม่ อ่ะ',
 'ขวด',
 'ทาน ได้ ค่ะ น้ำ ซุป ต้ม มาจาก หัวผักกาด ซีอิ้ว ขาว เกลือ แล น้ำตาล ค่ะ']

In [151]:
XTest_idx = []
for x in XTest:
  #print(x)
  XTest_idx.append(sent2idx(x))
  # print('Xtest_idx: ',Xtest_idx)
  if len(XTest_idx[-1]) > maxlen:
    XTest_idx[-1] =  XTest_idx[-1][:maxlen]
  else:
    XTest_idx[-1] = np.hstack((XTest_idx[-1], np.zeros(maxlen-len(XTest_idx[-1]))))
XTest_idx = np.array(XTest_idx)
print(XTest_idx.shape)

(2589, 473)


In [153]:
yTest_hat = model_LSTMth_PON.predict(XTest_idx)

yTest_true = np.argmax(YTest, axis=1).tolist()
yTest_hat = np.argmax(yTest_hat, axis=1).tolist()

# multilabel_confusion_matrix(ytrue, yhat)
accuracy_score(yTest_true, yTest_hat)

81/81 [==============================] - 17s 203ms/step


0.5098493626882966